const data = [
    { id: 1, name: 'John Doe' },
    { id: 2, name: 'Jane Doe' },
    { id: 3, name: 'Jim Doe' },
    { id: 4, name: 'Alice Smith' },
    { id: 5, name: 'Bob Smith' },
    { id: 6, name: 'Charlie Brown' },
    { id: 7, name: 'David Johnson' },
    { id: 8, name: 'Emma Davis' },
    { id: 9, name: 'Fiona White' },
    { id: 10, name: 'George Black' },
    { id: 11, name: 'Hannah Green' },
    { id: 12, name: 'Isaac Blue' },
    { id: 13, name: 'Jack Gray' },
    { id: 14, name: 'Katie Red' },
    { id: 15, name: 'Liam Orange' },
    { id: 16, name: 'Mia Purple' },
    { id: 17, name: 'Noah Yellow' },
    { id: 18, name: 'Olivia Pink' },
    { id: 19, name: 'Paul Cyan' },
    { id: 20, name: 'Quinn Magenta' },
    { id: 21, name: 'Rachel Violet' },
    { id: 22, name: 'Sam Brown' },
    { id: 23, name: 'Tina White' },
    { id: 24, name: 'Uma Black' },
    { id: 25, name: 'Victor Green' },
    { id: 26, name: 'Wendy Blue' },
    { id: 27, name: 'Xander Gray' },
    { id: 28, name: 'Yara Red' },
    { id: 29, name: 'Zane Orange' },
    { id: 30, name: 'Luna Purple' },
];
module.exports = {
    data
}